FileVersion = 1

[Project]
Name = "zstd-beef"
DefaultNamespace = "zstd"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\debug\\zstd_static.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\zstd_static.lib"]
